---
version: '2'
services:
  app:
    image: nicbet/docker-amber:0.28.0
    build: .
    command: amber watch
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    depends_on:
      - db
  db:
    image: postgres:10